services:
  - type: web
    name: libre-pdf-converter
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    startCommand: npm start
    region: oregon
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/chromium-browser
